export class Constants {
  static STAY_OPEN = 'stay_open'; // the class prevents the directive from closing component upon date select
  static MSG_ALREADY_LOGGED_IN = 'Redirecting, already logged in.';
  static MSG_LOGIN_TO_ACCESS = 'Redirecting, please log in to access the page.';
  static MSG_LOGGED_OUT = 'You have been logged out.';
  static MSG_DUPLICATE_MAIL = 'This email exists already.';
  static MSG_UNKNOWN_MAIL = 'This email does not exist.';
  static MSG_BAD_PASSWORD = 'This password is not correct.';
  static MSG_BAD_EMAIL = 'Bad email.';
  static MSG_REGISTRATION_SUCCESS = 'Registration successfull, please log in.';
  static MSG_FILTER_OVERWRITTEN = 'Filter was overwritten.';
  static MSG_SELECT_FILTER = 'Select a preset filter.';
  static MSG_FILTER_ADDED = 'New filter saved.';
  static SERVER_URL0 = 'http://localhost:5000/api/v1/';
  static SERVER_URL = 'https://airduino-server.herokuapp.com/api/v1/';
  static INACTIVE_PERIOD_LOGOUT = 30000; //seconds
  static DUMMY_LOCAL_ID = '11111';
  static DUMMY_TOKEN_ID = '11111';
  static MSG_ARE_U_SHURE = "Are you sure?";
  static MSG_CHECK_SOME_ROWS = "Check some rows.";
  static MSG_SELECT_ROW = "Select a row.";
  static MSG_SELECT_ONE_ROW = "Select only one row.";
  static MSG_NOT_A_GROUPOWNER = "Not a group owner row.";
  static TITLE_NEW_USER = "New user";
  static TITLE_EDIT_USER = "Edit user";
  static TITLE_NEW_DEVICE = "New device";
  static TITLE_EDIT_DEVICE = "Edit device";
  static TITLE_ADD_DEVICES = "Add devices";
  static MSG_MISSING_DATA_FILTER = "Choose filters to get data.";
}
